"""Example JARVIS skill script.

Contract:
  - stdin : JSON {"text": "<the spoken request>", "session": "<session id>"}
  - stdout: JSON {"reply": "<one short spoken sentence>"}  (best effort)

This skill turns a plain-text request into a timestamped markdown report file
inside data/skill_reports/ and returns the saved path.
"""
import json
import sys
from datetime import datetime
from pathlib import Path


def main() -> None:
    payload_raw = sys.stdin.read() if not sys.stdin.isatty() else "{}"
    try:
        payload = json.loads(payload_raw or "{}")
    except json.JSONDecodeError:
        payload = {}
    text = str(payload.get("text", "")).strip() or "JARVIS report"

    out_dir = Path(__file__).resolve().parent.parent / "data" / "skill_reports"
    out_dir.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    safe = "".join(ch if ch.isalnum() or ch in " -_" else "_" for ch in text)[:40].strip().replace(" ", "_")
    target = out_dir / f"{safe or 'report'}_{stamp}.md"
    target.write_text(
        f"# {text}\n\nGenerated by JARVIS at {datetime.now().strftime('%Y-%m-%d %H:%M')}.\n",
        encoding="utf-8",
    )
    print(json.dumps({"reply": f"Report saved to {target.name}."}))


if __name__ == "__main__":
    main()